### ISSUE TITLE
A "more accurate" method

### ISSUE THREAD

**Issue by Lazauya** [GarrettGunnell/Pixel-Sorting#2]
Hello, this problem has been nagging at me since I watched your video a while back. I wasn't sure where to write this, but this feels like a fine place. I am proposing a new method that should exactly sort the pixels in each row/column. I think it should be faster since you wouldn't need as many threads, and you could still do the bitonic sort. only half of them, and they should be reusable. Let me explain.

Here's an image explaining the flow: 
![pixelsortexp](https://github.com/GarrettGunnell/Pixel-Sorting/assets/12001517/5332b396-1bb8-42f4-aad9-a777b4a30973)

It's kinda scuffed, so sorry if it's hard to understand. The main takeaway is that we use the contrast mask in a different way. We first get our array of sort values, and we make sure the sort values are all in some range `[0, N)`. Then we iterate once over the values array, and if the mask jumps from a 0 to a 1 or a 1 to a 0, we add `N` to our offset which starts at 0. We add this offset to each pixel in the sort value array. Then we perform our sort on this new offset array. After it's sorted, each of the segments should remain contiguous and in the same place as they were before. Finally we do the reverse offset, subtracting as we go along to normalize back to our initial array where each element was in the range `[0, N)`. Below is some psuedo-code.

```
offset = 0
// add our offset and mask out the things that need to be sorted
for p in [0, P)
  if mask[p] != mask[p-1]
    offset += N
  // this is not technically necessary, actually, but if we want the non-sorted values to appear as 0 we can.
  sortedvals[p] *= mask
  sortedvals[p] += offset

// do the bitonic sort with as many threads as we want (max = image height / 2, obviously) 
sort(sortedvals)

// go backwards now, undoing the offset
for p in (P, 0]
  if mask[p] != mask[p+1]
    offset -= N
  sortedvals[p] -= offset
```

This lets us do a simple monotonic sort on each array, and so we don't have to spawn threads every frame, we can just constantly reuse the same exact threads for each frame and the upper bound should be reasonable small.

I would try implementing it, but I have limited time and I'm not sure how hard it would be to untangle the stuff already written.

**Comment by GarrettGunnell** [comment]
I also have limited time, but it'd be cool if you tried it out.
