### ISSUE TITLE
A potential way to increase performance

### ISSUE THREAD

**Issue by viliml** [GarrettGunnell/Pixel-Sorting#3]
Why don't you simply dispatch a separate group of 1024 threads for each pixel, and have the group perform a parallel bitonic merge sort if it lands on a span? For spans larger than 1024 pixels, divide it into 1024 blocks of (almost) equal size, pre-sort each block with insertion/selection sort or something (the blocks are going to be really small), then merge the blocks with a kind of blocked parallel bitonic merge sort in which you generalize `compareAndSwap` to a merge of blocks.

**Comment by GarrettGunnell** [comment]
Ideas are cheap, it'd be a lot more valuable if you simply implemented your idea yourself.

**Comment by viliml** [comment]
You should close #2 then too :)

**Comment by GarrettGunnell** [comment]
you're correct
